version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10-stretch

    working_directory: /go/src/github.com/giantswarm/micrologger

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go test ./...

      - run: go build

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
